// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxezcalicjxzbzamqxcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4ZXpjYWxpY2p4emJ6YW1xeGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyOTQ5MzQsImV4cCI6MjA2MDg3MDkzNH0.ROxAgdxJTgbkeiOh3EAQKE-xU9Zoi2eN1U493olkZ8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);